name: "CodeQL Java Static Analysis"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: '0 12 * * 0' # 매주 일요일 자동 실행

jobs:
  analyze:
    name: CodeQL Analyze (Pure Java Source)
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. CodeQL 초기화 (언어만 지정, 빌드 없음)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: ${{ matrix.language }}
          build-mode: none   # 🚨 빌드 완전히 비활성화

      # 3. CodeQL 분석 실행
      - name: Perform CodeQL Analysis
        uses: github/codeql-action/analyze@v3
