name: "Java Compile + CodeQL Analysis"

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  analyze:
    runs-on: ubuntu-latest

    permissions:
      actions: read
      contents: write
      security-events: write

    steps:
      # 1. 저장소 체크아웃
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. JDK 설치
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      # 3. 소스 컴파일 (bin 폴더 생성)
      - name: Compile Java sources
        run: |
          mkdir -p bin
          # 개별 파일 컴파일하면서 오류 파일 기록
          for f in $(find . -name "*.java"); do
            echo "Compiling $f"
            if ! javac -d bin "$f"; then
              echo "❌ Compile error in $f"
              cp "$f" "${f%.java}_update.java"
            fi
          done

      # 4. CodeQL 초기화 (순수 분석용)
      - name: Initialize CodeQL
        uses: github/codeql-action/init@v3
        with:
          languages: java
          build-mode: none   # 실제 빌드는 위에서 수행했음

      # 5. CodeQL 분석 실행
      - name: Run CodeQL Analysis
        uses: github/codeql-action/analyze@v3
        with:
          output: results

      # 6. 오류난 파일 커밋 (있을 경우만)
      - name: Commit update.java files
        run: |
          git config --global user.name "edumgt"
          git config --global user.email "kimdypm@gmail.com"

          if ls **/*_update.java 1> /dev/null 2>&1; then
            git add **/*_update.java
            git commit -m "Add _update.java files (compile errors)" || echo "No changes"
            git push
          else
            echo "✅ No compile errors. Nothing to commit."
          fi
